#' HT 9-well synthetic dataset
#'
#' A list containing a synthetic hydraulic tomography dataset with the true
#' transmissivity field, pumping test configurations, observation data, and
#' grid information.  Nine wells are arranged on a 3 × 3 regular grid inside a
#' 9 × 9 domain.
#'
#' @format A list with 4 elements:
#' \describe{
#'   \item{trueK}{a data frame, the true transmissivity field generated by
#'     \code{\link{random2d}}.  Columns are \code{x}, \code{y} (coordinates)
#'     and parameter realizations.}
#'   \item{qHT}{a list of data frames, one per pumping test.  Each data frame
#'     contains columns \code{Qp} (pumping rate in m\eqn{^3}/d \code{[L\eqn{^3}/T]}),
#'     \code{xp} and \code{yp} (coordinates of the pumping well \code{[L]}).}
#'   \item{oHT}{a list of data frames, one per pumping test.  Each data frame
#'     contains columns \code{data} (observed drawdown \code{[L]}), \code{x}
#'     and \code{y} (coordinates of the observation well \code{[L]}).}
#'   \item{grid}{a list returned by \code{\link{GenGrid}}, containing
#'     \code{nx}, \code{ny}, \code{grid} coordinates, etc.}
#' }
#' @source Generated in \code{vignettes/ht9_synthetic.Rmd}.
"ht9_synthetic"


