#' Plot the generated head distribution from Fsteady2dsim.
#' @return a plot showing contour.
#' @param steady2d a data.frame, the result of Fsteady2dsim (x,y,headchange).
#' @param plotshow a logical value, if TRUE, the plot will be shown.
#' @param plotfile a string, the path to save the plot.
#' @param plotwidth a numeric value, the width of the plot.
#' @param plotheight a numeric value, the height of the plot.
#' @param ifdrawdown a logical value, if true,  use drawdown, else using head change.
#' @param palette a string, the palette to use. could be magma, inferno, plasma, viridis, cividis, rocket, marko, turbo, or simply A-G.
#' @param Qinf The pumping test information in a data.frame (Qp,xp,yp).
#' @param Oinf The observation information in a data.frame (data,x,y).
#' @param title a string, the title of the plot.
#' @param z a string, the label of z axis.
#' @param xlab a string, the label of x axis.
#' @param ylab a string, the label of y axis.
#' @export
#' @examples
#' Qinf = data.frame(Qp=c(10,10),x=c(10.5,30.5),y=c(20.5,20.5))
#' s <- Fsteady2dsim(Qinf=Qinf)
#' Plotsteady2d(s,Qinf=Qinf,Oinf=data.frame(data=NA,x=c(15.5,25.5),y=c(20.5,20.5)))

Plotsteady2d <- function(s, palette="viridis",plotshow = TRUE,
                         plotfile = NULL, plotwidth = 10, plotheight = 10, ifdrawdown = TRUE,
                         Qinf = NULL, Oinf = NULL,
                         title =NULL, z = NULL,xlab="X/m",ylab="Y/m") {

  if (ifdrawdown) {
    s$solution = - s$solution
    if(!is.null(title)) title = "2D Steady-State Drawdown Distribution"
    if(!is.null(z))z = "Drawdown"
  } else {
    if(!is.null(title))title = "2D Steady-State Head Distribution"
    if(!is.null(z))z = "Head"
  }

  require('ggplot2')
  p = ggplot() +
    geom_tile(data = s, aes(x, y, fill = solution)) +
    scale_fill_viridis_c(option = palette)+
    labs(title = title, x = xlab, y = ylab, fill = z)
# add the location of pumping well and observation well if Qinf and Oinf are given.
  if(is.null(Qinf)==FALSE){
    p = p + geom_point(data=Qinf,aes(x=x,y=y),color='red',fill="white",shape=21,size=4)+
      geom_text(data=Qinf,aes(x=x,y=y,label=paste0("Q=",Qp)),color='red',vjust=-1)
  }
  if(is.null(Oinf)==FALSE){
    p = p + geom_point(data=Oinf,aes(x=x,y=y),color='yellow',fill="white",shape=22,size=3)
  }


  if(!is.null(plotfile)){
    ggsave(plotfile, width = plotwidth, height = plotheight)
  }
  if(plotshow) return(p)
}

#' Plot the generated T distribution from random2d.
#' @return a plot showing contour.
#' @param TT a data.frame, the result of Fsteady2dsim (x,y,transsimisivity).
#' @param plotshow a logical value, if TRUE, the plot will be shown.
#' @param plotfile a string, the path to save the plot.
#' @param plotwidth a numeric value, the width of the plot.
#' @param plotheight a numeric value, the height of the plot.
#' @param iflog a logical value, if true,  use log(T), else using T.
#' @param palette a string, the palette to use. could be magma, inferno, plasma, viridis, cividis, rocket, marko, turbo, or simply A-G.
#' @param title a string, the title of the plot.
#' @param z a string, the label of z axis.
#' @param xlab a string, the label of x axis.
#' @param ylab a string, the label of y axis.
#' @export
#' @examples
#' TT= random2d()
#' Plotparameter2d(TT,iflog=T)
#' TT= random2d(geo=list(me=0,var=1,geomod="Exp",anis=c(90,0.2),range=30,nugget=0))
#' Plotparameter2d(TT,iflog=T)

Plotparameter2d <- function(TT, palette="viridis",plotshow = TRUE,
                         plotfile = NULL, plotwidth = 10, plotheight = 10, iflog = FALSE,
                         title =NULL, z = NULL,xlab="X/m",ylab="Y/m") {

  if (iflog) {
    TT$Tp = log(TT$Tp)
    if(!is.null(title)) title = "2D log-transformed Transimisivity"
    if(!is.null(z))z = "log(T) [L2/T]"
  } else {
    if(!is.null(title)) title = "2D Transimisivity"
    if(!is.null(z)) z = "T [L2/T]"
  }

  require('ggplot2')
  p = ggplot(TT, aes(x, y, fill = Tp)) +
    geom_tile() +
    scale_fill_viridis_c(option = palette)+
    labs(title = title, x = xlab, y = ylab, fill = z)



  if(!is.null(plotfile)){
    ggsave(plotfile, width = plotwidth, height = plotheight)
  }
  if(plotshow) return(p)
}

#' now we can choose the best iteration to plot.
#' @export
#' @param niterm the number of iterations.
#' @param grid grid generated by GenGrid function using domain information.
#' @param oHT list of observation information. list(data.frame(data,x,y))
#' @param iterdf the data.frame of iterations.
#' @param trueK the true K field (used in synthetic case).
#' @param p1title title of plot 1 (value of lnT).
#' @param p1z z label of plot 1.
#' @param p1xlab x label of plot 1.
#' @param p1ylab y label of plot 1.
#' @param p2title title of plot 2 (value of lnT variance).
#' @param p2z z label of plot 2.
#' @param p2xlab x label of plot 2.
#' @param p2ylab y label of plot 2.
#' @param p3title title of plot 3(head scatter).
#' @param p3xlab x label of plot 3.
#' @param p3ylab y label of plot 3.
#' @param p4title title of plot 4(lnT scatter).
#' @param p4xlab x label of plot 4.
#' @param p4ylab y label of plot 4.
#' @examples
#' set.seed(100)
#' trueK <- random2d(nsim=1)
#' TT <- trueK[,-c(1,2)]
#' domain=c(40,40,0,40,0,40)
#' grid = GenGrid(domain)
#' Qinf1=data.frame(Qp=10,xp=20.5,yp=20.5)
#' qHT <- list(test1 = Qinf1)
#' trueh <- Fsteady2dsim(TT=TT,Qinf=Qinf1,grid=grid)
#' trueh <- trueh$solution
#' locx = c(15,18,22,25,30)
#' locy = c(15,18,22,25,30)
#' loc= expand.grid(x=locx,y=locy)
#' Oinf <- data.frame(data=NA,x=loc$x,y=loc$y)
#' Oinf <- getOelem(grid = grid)
#' Oinf$data <- trueh[Oinf$nelem]
#' oHT <- list(test1 = Oinf)
#' result <- Finverse(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,grid=grid,iterdf = result,oHT = oHT,trueK=trueK)
inversePlot <- function(niterm=1,grid,iterdf,oHT,trueK=NULL,
                        p1title= "Est. lnT value",p1z= "lnT",p1xlab="X/m",p1ylab="Y/m",
                        p2title= 'Est. var. of lnT',p2z= "var. of lnT",p2xlab="X/m",p2ylab="Y/m",
                        p3title= "Drawdown scatter",p3xlab="Obs. Drawdown/m",p3ylab="Sim. Drawdown/m",
                        p4title= "lnT scatter",p4xlab="True lnT /(m2/d)",p4ylab="Est. lnT /(m2/d)"){
  # niterm = 5
  # note that trueh is actually a list contains many pumping tests.
  require(dplyr)
  oHTdf = bind_rows(oHT,.id='id')
  # np <- sapply(trueh,length) # get the number of observations for each test.
  # ntest <- rep("test1",np[1])
  # if(length(np)>=2){
  #   for (i in 2:length(np)){
  #     ntest <- append(ntest,rep(paste0("test",i),np[i]))
  #   }
  # }

  trueh <- oHTdf$data # the observation data in a vector.
  df <- data.frame(x=grid$grid$x,y=grid$grid$y,v=iterdf[[niterm]]$meanT,var=iterdf[[niterm]]$varT)
  library(ggplot2)
  p1<- ggplot(df) +
    aes(x = x, y = y, fill = v) +
    geom_tile()+
    scale_fill_viridis_c(option = "viridis", direction = 1)+
    labs(title = p1title, x = p1xlab, y = p1ylab, fill = p1z)
  p2 <- ggplot(df) +
    aes(x = x, y = y, fill = var) +
    geom_tile()+
    scale_fill_viridis_c(option = "viridis", direction = 1)+
    labs(title = p2title, x = p2xlab, y = p2ylab, fill = p2z)
  # change it to drawdown not head.
  dfh <- data.frame(trueh=-trueh,simh=-iterdf[[niterm]]$meanobsh,varh=iterdf[[niterm]]$varobsh,ntest=oHTdf$id)
  #https://www.roelpeters.be/how-to-add-a-regression-equation-and-r-squared-in-ggplot2/
  #https://rpkgs.datanovia.com/ggpubr/reference/stat_regline_equation.html
  require(ggpubr)
  p3 <- ggplot(dfh) +
    geom_errorbar(aes(x = trueh,ymin=simh-varh^0.5,ymax=simh+varh^0.5),width=0.02,color="gray")+
    geom_point(size=4,aes(x = trueh, y = simh,colour=ntest))+
    geom_smooth(method = "lm", aes(x = trueh, y = simh),se=FALSE) +
    stat_regline_equation(aes(x = trueh, y = simh),label.y = -0.5) +
    stat_cor( aes(x = trueh, y = simh),label.y = -1) +
    labs(title = p3title, x = p3xlab, y = p3ylab)

  p1
  p2
  p3

  if(!is.null(trueK)){
    # scatterks <- data.frame(x=log(trueK$Tp),y=log(iterdf[[niterm]]$meanT))
    scatterks <- data.frame(x=log(trueK$Tp),y=iterdf[[niterm]]$meanT) # inverse directly store lnT. 2026.01.01
    p4 <- ggplot(scatterks) +
      aes(x,y) +
      geom_point(size=1)+
      geom_smooth(method = "lm", se=T) +
      stat_regline_equation(label.y = -0.5)+
      labs(title = p4title, x = p4xlab, y = p4ylab)
  }
  if(!is.null(trueK))
    return(list(lnk=p1,varlnk=p2,lnkscatter=p4,headscatter=p3))
  else
    return(list(lnk=p1,varlnk=p2,headscatter=p3))
}
