#' make a Monte Carlo inverse simulation.
#' HT simulations.
#' forward information. domain, bc, pump loc,
#' observation location and value.
#' geostatistical prior information.
#' hyper parameters --- nsim, itermax, etc.
#' @param domain grid c(nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param qHT list of pumping test information.
#' @param nsim number of ensemble, default 50.
#' @param itermax maximum number of iterations.
#' @param varmeanTmax maximum variance of mean T.
#' @param rmsemin minimum rmse.
#' @param mul stablizer.
#' @param oHT list of observation information. list(data.frame(data,x,y))
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @return list of iteration data.
#' @export
#' @examples
#' set.seed(100)
#' trueK <- random2d(nsim=1)
#' TT <- trueK[,-c(1,2)]
#' domain=c(40,40,0,40,0,40)
#' grid = GenGrid(domain)
#' Qinf1=data.frame(Qp=10,xp=20.5,yp=20.5)
#' qHT <- list(test1 = Qinf1)
#' trueh <- Fsteady2dsim(TT=TT,Qinf=Qinf1,domain=domain)
#' locx = c(15,18,22,25,30)
#' locy = c(15,18,22,25,30)
#' loc= expand.grid(x=locx,y=locy)
#' Oinf1 <- data.frame(data=NA,x=loc$x,y=loc$y)
#' Oinf1 <- samData(grid = grid,Oinf = Oinf1,h=trueh$solution)
#' oHT <- list(test1 = Oinf1)
#' result <- Finverse(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK)
#' Qinf2=data.frame(Qp=10,xp=10.5,yp=10.5)
#' trueh2 <- Fsteady2dsim(TT=TT,Qinf=Qinf2,domain=domain)
#' Oinf2 <- Oinf1
#' Oinf2 <- samData(grid = grid,Oinf = Oinf2,h=trueh2$solution)
#' oHT <- list(test1 = Oinf1,test2 = Oinf2)
#' qHT <- list(test1 = Qinf1,test2 = Qinf2)
#' result <- Finverse(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK)

Finverse <- function(
    domain=c(40,40,0,40,0,40),
    grid = NULL,
    qHT=list(data.frame(Qp=10,x=20.5,y=20.5)), # should be list since it is HT.
    nsim=50,
    itermax=5,
    varmeanTmax =5,
    rmsemin = 0,
    mul=1.0,
    oHT= list(data.frame(data=-1,x=11,y=11)),
    lrw=160000) # should be list since multiple pumping test.
{
  set.seed(200)
  ### record the time so to see how long it takes.
  startTime <- Sys.time()
  if(is.null(grid))grid = GenGrid(domain)

  #nsim = 50
  nHT <- length(qHT) # number of pumping test.also list length of oHT.
  trueobshHT <- list()
  loc_obsHT <- list()
  for (i in 1:nHT){
    oinf <- oHT[[i]]
    oelemdf <- getOelem(domain = domain,grid = grid,Oinf = oinf)
    loc_obsHT[[i]] <- oelemdf$nelem
    trueobshHT[[i]] <- oinf$data
  }
  trueobsh <- unlist(trueobshHT) # the data format in HT is a list.
  nobs <- length(trueobsh)

  yy <- random2d(nsim=nsim,grid = grid)
  # initial ensemble.
  Tnew <- yy[,-c(1,2)]
  # nelem*nsim
  ### get the variance map of Tnew.
  ### this should goes with iterations.
  niter <- 1
  varmeanT <- 0
  rmse <- 1e10
  #itermax <- 100
  #varmeanTmax <- 5
  #rmsemin <- 0
  #mul <- 1.0 # stablizer.
  msgdf <- data.frame(niter = niter,varmeanT=varmeanT, rmse=rmse)
  iterdf <- list()

  # start of the itertion loop.
  while(niter<=itermax & varmeanT<varmeanTmax & rmse>rmsemin){
    varT <- apply(log(Tnew),1,var)
    meanT <- apply(log(Tnew),1,mean)
    varmeanT = var(meanT)
    # from Tnew to h.

    # hHT <- list()
    # for (j in 1:nHT){
    #   Qinf <- qHT[[j]]  # the information of jth pumping test.
    #   h <- Fsteady2dsim(TT=Tnew[,1],Qinf=Qinf)$solution
    #   for(i in 2:nsim){
    #   h <- rbind(h,Fsteady2dsim(TT=Tnew[,i],Qinf=Qinf)$solution)
    #   }
    #   # h: nsim*nelem
    #   obsh<- h[,loc_obsHT[[j]]]
    #   hHT[[j]] <- obsh # store the j th pumping test observations.
    # }
    hHT <- lapply(1:nHT, function(j) {
      Qinf <- qHT[[j]]
      # 使用 lapply 生成所有模拟结果
      h_list <- lapply(1:nsim, function(i){
        tmp = Fsteady2dsim(grid = grid, TT = Tnew[, i], Qinf = Qinf,lrw=lrw)$solution
        index = loc_obsHT[[j]]
        tmp[index]
      }

      )
      # 一次性合并所有结果
      h_matrix <- do.call(rbind, h_list)
    })


    # obsh: nsim*nobs
    if(nHT>1) obsh <- do.call("cbind",hHT) else obsh <- hHT[[1]]

    # get the head variance for each observation.
    varobsh <- apply(obsh,2,var)
    meanobsh <- apply(obsh,2,mean)
    # get the misfit.
    weigs <- 1/varobsh/sum(1/varobsh)
    rmse <- mean((trueobsh - meanobsh)^2*weigs)^0.5
    l2 <- mean((trueobsh - meanobsh)^2)^0.5
    l1 <- mean(abs(trueobsh - meanobsh))

    # get the covariance of h and h-T
    covh <- cov(obsh)
    data = list(obsh,t(log(Tnew)))
    # notice it is lnK rather than K.
    cc <- function(obsh,TT){
      covhk = cov(obsh,TT)
    }
    covhk = suppressWarnings(multiApply::Apply(data,target_dims = list(1,1),cc))

    # add stablizer term.
    covh1 <- covh
    #diag(covh1) <-  (1+mul)*diag(covh)
    diag(covh1) <-  rep((1+mul)*max(diag(covh)),nobs)
    #### now we need to invert the covariance function and get the covh-1* %*% covhf
    a = solve(covh1,covhk[[1]])
    # a in nobs*nelem

    ### now we update the k value based on the difference between obs. and sim.
    for(i in 1:nsim){
      Tnew[,i] <- Tnew[,i] *  exp( t(a) %*% (trueobsh - obsh[i,]))
    }

    msg <- paste('niter =', niter,
                 'varmeanT=', round(varmeanT,4),
                 'rmse=',round(rmse,4),
                 "l2=",round(l2,4),
                 "l1=",round(l1,4))
    msgdf <- rbind(msgdf,c(niter,varmeanT,rmse))
    print(msg)
    ### we need to store the iteration data.
    iterdf[[niter]] <- list(meanT = as.vector(meanT), varT = as.vector(varT), meanobsh = meanobsh, varobsh = varobsh)
    niter <- niter + 1
    mul <- mul/1.05

    ### iteration over time.
  }
  endTime <- Sys.time()
  # get the time in seconds or mins.
  print(paste("The computational time takes ", round(endTime-startTime,digits=2),"seconds."))
  return(iterdf)
}
