#' make a Monte Carlo inverse simulation.
#' HT simulations.
#' forward information. domain, bc, pump loc,
#' observation location and value.
#' geostatistical prior information.
#' hyper parameters --- nsim, itermax, etc.
#' @param domain grid c(nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param qHT list of pumping test information.
#' @param nsim number of ensemble, default 50.
#' @param itermax maximum number of iterations.
#' @param varmeanTmax maximum variance of mean T.
#' @param rmsemin minimum rmse.
#' @param mul stablizer default 1.
#' @param decay decay of stablizer,default 1.05.
#' @param oHT list of observation information. list(data.frame(data,x,y))
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @param geo prior information for lnT, geostatistical features: list(mean,variance,covarirance_function,anisotropy,range,nugget)
#' @return list of iteration data.
#' @export
#' @examples
#' set.seed(100)
#' trueK <- random2d(nsim=1)
#' TT <- trueK[,-c(1,2)]
#' domain=c(40,40,0,40,0,40)
#' grid = GenGrid(domain)
#' Qinf1=data.frame(Qp=10,xp=20.5,yp=20.5)
#' qHT <- list(test1 = Qinf1)
#' trueh <- Fsteady2dsim(TT=TT,Qinf=Qinf1,domain=domain)
#' locx = c(15,18,22,25,30)
#' locy = c(15,18,22,25,30)
#' loc= expand.grid(x=locx,y=locy)
#' Oinf1 <- data.frame(data=NA,x=loc$x,y=loc$y)
#' Oinf1 <- samData(grid = grid,Oinf = Oinf1,h=trueh$solution)
#' oHT <- list(test1 = Oinf1)
#' result <- Finverse(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK,grid=grid)
#' Qinf2=data.frame(Qp=10,xp=10.5,yp=10.5)
#' trueh2 <- Fsteady2dsim(TT=TT,Qinf=Qinf2,domain=domain)
#' Oinf2 <- Oinf1
#' Oinf2 <- samData(grid = grid,Oinf = Oinf2,h=trueh2$solution)
#' oHT <- list(test1 = Oinf1,test2 = Oinf2)
#' qHT <- list(test1 = Qinf1,test2 = Qinf2)
#' result <- Finverse(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK,grid=grid)

Finverse <- function(
    domain=c(40,40,0,40,0,40),
    grid = NULL,
    qHT=list(data.frame(Qp=10,x=20.5,y=20.5)), # should be list since it is HT.
    nsim=50,
    itermax=5,
    varmeanTmax =5,
    rmsemin = 0,
    mul=1.0,
    decay = 1.05,
    oHT= list(data.frame(data=-1,x=11,y=11)),
    lrw=160000,
    geo=list(me=0,var=1,geomod="Exp",anis=c(90,1),range=30,nugget=0)) # should be list since multiple pumping test.
{
  #1. ----- before iteration (generating ensemble.....)----------
  set.seed(200)
  ### record the time so to see how long it takes.
  startTime <- Sys.time()
  if(is.null(grid))grid = GenGrid(domain)

  #nsim = 50
  nHT <- length(qHT) # number of pumping test.also list length of oHT.
  trueobshHT <- list()
  loc_obsHT <- list()
  for (i in 1:nHT){
    oinf <- oHT[[i]]
    oelemdf <- getOelem(domain = domain,grid = grid,Oinf = oinf)
    loc_obsHT[[i]] <- oelemdf$nelem
    trueobshHT[[i]] <- oinf$data
  }
  trueobsh <- unlist(trueobshHT) # the data format in HT is a list.
  nobs <- length(trueobsh)

  yy <- random2d(nsim=nsim,grid = grid, geo = geo)
  # initial ensemble.
  Tnew <- yy[,-c(1,2)]
  # nelem*nsim
  ### get the variance map of Tnew.
  ### this should goes with iterations.
  niter <- 1
  varmeanT <- 0
  rmse <- 1e10
  #itermax <- 100
  #varmeanTmax <- 5
  #rmsemin <- 0
  #mul <- 1.0 # stablizer.
  msgdf <- data.frame(niter = niter,varmeanT=varmeanT, rmse=rmse)
  iterdf <- list()
  #1. ----- before iteration----------0.94 0.00 0.94 (blh_synthetic)
  # start of the itertion loop.
  while(niter<=itermax & varmeanT<varmeanTmax & rmse>rmsemin){
  #2. -----------get the obsh......------
     varT <- apply(log(Tnew),1,var)
    meanT <- apply(log(Tnew),1,mean)
    varmeanT = var(meanT)
    # from Tnew to h.

    # hHT <- list()
    # for (j in 1:nHT){
    #   Qinf <- qHT[[j]]  # the information of jth pumping test.
    #   h <- Fsteady2dsim(TT=Tnew[,1],Qinf=Qinf)$solution
    #   for(i in 2:nsim){
    #   h <- rbind(h,Fsteady2dsim(TT=Tnew[,i],Qinf=Qinf)$solution)
    #   }
    #   # h: nsim*nelem
    #   obsh<- h[,loc_obsHT[[j]]]
    #   hHT[[j]] <- obsh # store the j th pumping test observations.
    # }
    ### upgrade to parallel computing...........
     # require(parallel)
     # n = parallel::detectCores() - 1
     # print(paste("using cores of ", n))
     # cl = parallel::makeCluster(n)

    hHT <- lapply(1:nHT, function(j) {
      Qinf <- qHT[[j]]
      # 使用 lapply 生成所有模拟结果
       h_list <- lapply(1:nsim, function(i){
         tmp = Fsteady2dsim(grid = grid, TT = Tnew[, i], Qinf = Qinf,lrw=lrw)$solution
         index = loc_obsHT[[j]]
         tmp[index]
       })


      # https://hansekbrand.se/code/clusterExport.html
      ## it seems parallel package has some problem for local variable broadcasting.
      #  clusterExport(cl,varlist = c("Fsteady2dsim"))
      #  clusterExport(cl,varlist = c("nsim","grid","Qinf","Tnew",'lrw'))
      #   h_list <- parLapply(cl,1:nsim, function(i){
      #     tmp = Fsteady2dsim(grid = grid, TT = Tnew[, i], Qinf = Qinf,lrw=lrw)$solution
      #     index = loc_obsHT[[j]]
      #     tmp[index]
      #   }
      #   )
      # 一次性合并所有结果
      h_matrix <- do.call(rbind, h_list)
    })

    # Stop the cluster
    # stopCluster(cl)
    # obsh: nsim*nobs
    if(nHT>1) obsh <- do.call("cbind",hHT) else obsh <- hHT[[1]]
  #2. -----------get the obsh......------10.51  0.41 10.97

    # get the head variance for each observation.
  #3. ----------- get the covh and covhk..............
    varobsh <- apply(obsh,2,var)
    meanobsh <- apply(obsh,2,mean)
    # get the misfit.
    weigs <- 1/varobsh/sum(1/varobsh)
    rmse <- mean((trueobsh - meanobsh)^2*weigs)^0.5
    l2 <- mean((trueobsh - meanobsh)^2)^0.5
    l1 <- mean(abs(trueobsh - meanobsh))

    # get the covariance of h and h-T
    # covh <- cov(obsh)
    # data = list(obsh,t(log(Tnew)))
    # # notice it is lnK rather than K.
    # cc <- function(obsh,TT){
    #   covhk = cov(obsh,TT)
    # }
    # covhk = suppressWarnings(multiApply::Apply(data,target_dims = list(1,1),cc))
    #3. ----------- get the covh and covhk.............. blh 37.38  0.05 37.46
    ## we now update the covariance calculation method.
    # obsh --- n_ensemble * n_obs.
    covh = cov(obsh) # the default is y = x
    # covh n_obs*n_obs
    tmpy = t(log(Tnew))
    covhk = cov(obsh,tmpy)
    # add stablizer term.
    #4. ----------- solve covh ..............
    covh1 <- covh
    #diag(covh1) <-  (1+mul)*diag(covh)
    diag(covh1) <-  rep((1+mul)*max(diag(covh)),nobs)
    #### now we need to invert the covariance function and get the covh-1* %*% covhf
    #a = solve(covh1,covhk[[1]])
    a = solve(covh1,covhk)
    # a in nobs*nelem

    ### now we update the k value based on the difference between obs. and sim.
    for(i in 1:nsim){
      Tnew[,i] <- Tnew[,i] *  exp( t(a) %*% (trueobsh - obsh[i,]))
    }

    msg <- paste('niter =', niter,
                 'varmeanT=', round(varmeanT,4),
                 'rmse=',round(rmse,4),
                 "l2=",round(l2,4),
                 "l1=",round(l1,4))
    msgdf <- rbind(msgdf,c(niter,varmeanT,rmse))
    #4. ----------- solve covh ..............0.42 0.07 0.49
    print(msg)
    ### we need to store the iteration data.
    iterdf[[niter]] <- list(meanT = as.vector(meanT), varT = as.vector(varT), meanobsh = meanobsh, varobsh = varobsh)
    if(niter == 1){
      et = Sys.time()
      print(" -------------------The Computational time for one iteration--------- ")
      print( difftime(et,startTime))
      print(" -------------------The Computational time for one iteration--------- ")
    }
    niter <- niter + 1
    mul <- mul/decay

    ### iteration over time.
  }
  endTime <- Sys.time()
  # get the time in seconds or mins.
  print("-------------------The Computational--------- ")
  print(difftime(endTime,startTime))
  print("-------------------The Computational--------- ")
  return(iterdf)
}


#' make a Monte Carlo inverse simulation.
#' HT simulations.
#' forward information. domain, bc, pump loc,
#' observation location and value.
#' geostatistical prior information.
#' hyper parameters --- nsim, itermax, etc.
#' @param domain grid c(nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param qHT list of pumping test information.
#' @param nsim number of ensemble, default 50.
#' @param itermax maximum number of iterations.
#' @param varmeanTmax maximum variance of mean T.
#' @param rmsemin minimum rmse.
#' @param mul stablizer default 1.
#' @param decay decay of stablizer,default 1.05.
#' @param oHT list of observation information. list(data.frame(data,x,y))
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @param geo prior information for lnT, geostatistical features: list(mean,variance,covarirance_function,anisotropy,range,nugget)
#' @return list of iteration data.
#' @export
#' @examples
#' set.seed(100)
#' trueK <- random2d(nsim=1)
#' TT <- trueK[,-c(1,2)]
#' domain=c(40,40,0,40,0,40)
#' grid = GenGrid(domain)
#' Qinf1=data.frame(Qp=10,xp=20.5,yp=20.5)
#' qHT <- list(test1 = Qinf1)
#' trueh <- Fsteady2dsim(TT=TT,Qinf=Qinf1,domain=domain)
#' locx = c(15,18,22,25,30)
#' locy = c(15,18,22,25,30)
#' loc= expand.grid(x=locx,y=locy)
#' Oinf1 <- data.frame(data=NA,x=loc$x,y=loc$y)
#' Oinf1 <- samData(grid = grid,Oinf = Oinf1,h=trueh$solution)
#' oHT <- list(test1 = Oinf1)
#' result <- Finverse2(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK,grid=grid)
#' Qinf2=data.frame(Qp=10,xp=10.5,yp=10.5)
#' trueh2 <- Fsteady2dsim(TT=TT,Qinf=Qinf2,domain=domain)
#' Oinf2 <- Oinf1
#' Oinf2 <- samData(grid = grid,Oinf = Oinf2,h=trueh2$solution)
#' oHT <- list(test1 = Oinf1,test2 = Oinf2)
#' qHT <- list(test1 = Qinf1,test2 = Qinf2)
#' result <- Finverse2(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK,grid=grid)

Finverse2 <- function(
    domain=c(40,40,0,40,0,40),
    grid = NULL,
    qHT=list(data.frame(Qp=10,x=20.5,y=20.5)), # should be list since it is HT.
    nsim=50,
    itermax=5,
    varmeanTmax =5,
    rmsemin = 0,
    mul=1.0,
    decay = 1.05,
    oHT= list(data.frame(data=-1,x=11,y=11)),
    lrw=160000,
    geo=list(me=0,var=1,geomod="Exp",anis=c(90,1),range=30,nugget=0)) # should be list since multiple pumping test.
{
  #1. ----- before iteration (generating ensemble.....)----------
  set.seed(200)
  ### record the time so to see how long it takes.
  startTime <- Sys.time()
  if(is.null(grid))grid = GenGrid(domain)

  #nsim = 50
  nHT <- length(qHT) # number of pumping test.also list length of oHT.
  # create the ij grid.
  library('foreach')
  #isim = 1:nsim
  #jHT = 1: nHT
  #ij = expand.grid(isim = isim, jHT = jHT)
  trueobshHT <- list()
  loc_obsHT <- list()
  for (i in 1:nHT){
    oinf <- oHT[[i]]
    oelemdf <- getOelem(domain = domain,grid = grid,Oinf = oinf)
    loc_obsHT[[i]] <- oelemdf$nelem
    trueobshHT[[i]] <- oinf$data
  }
  trueobsh <- unlist(trueobshHT) # the data format in HT is a list.
  nobs <- length(trueobsh)

  yy <- random2d(nsim=nsim,grid = grid, geo = geo)
  # initial ensemble.
  Tnew <- yy[,-c(1,2)]
  # nelem*nsim
  ### get the variance map of Tnew.
  ### this should goes with iterations.
  niter <- 1
  varmeanT <- 0
  rmse <- 1e10
  #itermax <- 100
  #varmeanTmax <- 5
  #rmsemin <- 0
  #mul <- 1.0 # stablizer.
  msgdf <- data.frame(niter = niter,varmeanT=varmeanT, rmse=rmse)
  iterdf <- list()
  #1. ----- before iteration----------0.94 0.00 0.94 (blh_synthetic)
  # start of the itertion loop.
  while(niter<=itermax & varmeanT<varmeanTmax & rmse>rmsemin){
    #2. -----------get the obsh......------
    varT <- apply(log(Tnew),1,var)
    meanT <- apply(log(Tnew),1,mean)
    varmeanT = var(meanT)

# for each test and each nsim, simulate.

    hHT <- lapply(1:nHT, function(j) {
      Qinf <- qHT[[j]]
      # 使用 lapply 生成所有模拟结果
      h_mat <- foreach(i= 1:nsim,.combine=rbind) %do% {
        tmp = Fsteady2dsim(grid = grid, TT = Tnew[, i], Qinf = Qinf,lrw=lrw)$solution
        index = loc_obsHT[[j]]
        tmp[index]
      }
    })

    # Stop the cluster
    # stopCluster(cl)
    # obsh: nsim*nobs
    if(nHT>1) obsh <- do.call("cbind",hHT) else obsh <- hHT[[1]]
    #2. -----------get the obsh......------10.51  0.41 10.97

    # get the head variance for each observation.
    #3. ----------- get the covh and covhk..............
    varobsh <- apply(obsh,2,var)
    meanobsh <- apply(obsh,2,mean)
    # get the misfit.
    weigs <- 1/varobsh/sum(1/varobsh)
    rmse <- mean((trueobsh - meanobsh)^2*weigs)^0.5
    l2 <- mean((trueobsh - meanobsh)^2)^0.5
    l1 <- mean(abs(trueobsh - meanobsh))

    ## we now update the covariance calculation method.
    # obsh --- n_ensemble * n_obs.
    covh = cov(obsh) # the default is y = x
    # covh n_obs*n_obs
    tmpy = t(log(Tnew))
    covhk = cov(obsh,tmpy)
    # add stablizer term.
    #4. ----------- solve covh ..............
    covh1 <- covh
    #diag(covh1) <-  (1+mul)*diag(covh)
    diag(covh1) <-  rep((1+mul)*max(diag(covh)),nobs)
    #### now we need to invert the covariance function and get the covh-1* %*% covhf
    #a = solve(covh1,covhk[[1]])
    a = solve(covh1,covhk)
    # a in nobs*nelem

    ### now we update the k value based on the difference between obs. and sim.
    for(i in 1:nsim){
      Tnew[,i] <- Tnew[,i] *  exp( t(a) %*% (trueobsh - obsh[i,]))
    }

    msg <- paste('niter =', niter,
                 'varmeanT=', round(varmeanT,4),
                 'rmse=',round(rmse,4),
                 "l2=",round(l2,4),
                 "l1=",round(l1,4))
    msgdf <- rbind(msgdf,c(niter,varmeanT,rmse))
    #4. ----------- solve covh ..............0.42 0.07 0.49
    print(msg)
    ### we need to store the iteration data.
    iterdf[[niter]] <- list(meanT = as.vector(meanT), varT = as.vector(varT), meanobsh = meanobsh, varobsh = varobsh)
    if(niter == 1){
      et = Sys.time()
      print(" -------------------The Computational time for one iteration--------- ")
      print( difftime(et,startTime))
      print(" -------------------The Computational time for one iteration--------- ")
    }
    niter <- niter + 1
    mul <- mul/decay

    ### iteration over time.
  }
  endTime <- Sys.time()
  # get the time in seconds or mins.
  print("-------------------The Computational--------- ")
  print(difftime(endTime,startTime))
  print("-------------------The Computational--------- ")
  return(iterdf)
}



#' make a Monte Carlo inverse simulation.
#' HT simulations.
#' forward information. domain, bc, pump loc,
#' observation location and value.
#' geostatistical prior information.
#' hyper parameters --- nsim, itermax, etc.
#' @param domain grid c(nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param qHT list of pumping test information.
#' @param nsim number of ensemble, default 50.
#' @param itermax maximum number of iterations.
#' @param varmeanTmax maximum variance of mean T.
#' @param rmsemin minimum rmse.
#' @param mul stablizer default 1.
#' @param decay decay of stablizer,default 1.05.
#' @param oHT list of observation information. list(data.frame(data,x,y))
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @param ncore integer, the number of cores in parallel.
#' @param geo prior information for lnT, geostatistical features: list(mean,variance,covarirance_function,anisotropy,range,nugget)
#' @return list of iteration data.
#' @export
#' @examples
#' set.seed(100)
#' trueK <- random2d(nsim=1)
#' TT <- trueK[,-c(1,2)]
#' domain=c(40,40,0,40,0,40)
#' grid = GenGrid(domain)
#' Qinf1=data.frame(Qp=10,xp=20.5,yp=20.5)
#' qHT <- list(test1 = Qinf1)
#' trueh <- Fsteady2dsim(TT=TT,Qinf=Qinf1,domain=domain)
#' locx = c(15,18,22,25,30)
#' locy = c(15,18,22,25,30)
#' loc= expand.grid(x=locx,y=locy)
#' Oinf1 <- data.frame(data=NA,x=loc$x,y=loc$y)
#' Oinf1 <- samData(grid = grid,Oinf = Oinf1,h=trueh$solution)
#' oHT <- list(test1 = Oinf1)
#' result <- Finverse3(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK,grid=grid)
#' Qinf2=data.frame(Qp=10,xp=10.5,yp=10.5)
#' trueh2 <- Fsteady2dsim(TT=TT,Qinf=Qinf2,domain=domain)
#' Oinf2 <- Oinf1
#' Oinf2 <- samData(grid = grid,Oinf = Oinf2,h=trueh2$solution)
#' oHT <- list(test1 = Oinf1,test2 = Oinf2)
#' qHT <- list(test1 = Qinf1,test2 = Qinf2)
#' result <- Finverse3(grid =grid, qHT = qHT, oHT = oHT)
#' inversePlot(niterm=5,iterdf = result,oHT = oHT,trueK=trueK,grid=grid)

Finverse3 <- function(
    domain=c(40,40,0,40,0,40),
    grid = NULL,
    qHT=list(data.frame(Qp=10,x=20.5,y=20.5)), # should be list since it is HT.
    nsim=50,
    itermax=5,
    varmeanTmax =5,
    rmsemin = 0,
    mul=1.0,
    decay = 1.05,
    oHT= list(data.frame(data=-1,x=11,y=11)),
    lrw=160000,
    ncore =10,
    geo=list(me=0,var=1,geomod="Exp",anis=c(90,1),range=30,nugget=0)) # should be list since multiple pumping test.
{
  #1. ----- before iteration (generating ensemble.....)----------
  set.seed(200)
  ### record the time so to see how long it takes.
  startTime <- Sys.time()
  if(is.null(grid))grid = GenGrid(domain)

  #nsim = 50
  nHT <- length(qHT) # number of pumping test.also list length of oHT.
  # create the ij grid.
  library('foreach')
  library("doParallel")
  #isim = 1:nsim
  #jHT = 1: nHT
  #ij = expand.grid(isim = isim, jHT = jHT)
  trueobshHT <- list()
  loc_obsHT <- list()
  for (i in 1:nHT){
    oinf <- oHT[[i]]
    oelemdf <- getOelem(domain = domain,grid = grid,Oinf = oinf)
    loc_obsHT[[i]] <- oelemdf$nelem
    trueobshHT[[i]] <- oinf$data
  }
  trueobsh <- unlist(trueobshHT) # the data format in HT is a list.
  nobs <- length(trueobsh)

  yy <- random2d(nsim=nsim,grid = grid, geo = geo)
  # initial ensemble.
  Tnew <- yy[,-c(1,2)]
  # nelem*nsim
  ### get the variance map of Tnew.
  ### this should goes with iterations.
  niter <- 1
  varmeanT <- 0
  rmse <- 1e10
  #itermax <- 100
  #varmeanTmax <- 5
  #rmsemin <- 0
  #mul <- 1.0 # stablizer.
  msgdf <- data.frame(niter = niter,varmeanT=varmeanT, rmse=rmse)
  iterdf <- list()
  #1. ----- before iteration----------0.94 0.00 0.94 (blh_synthetic)
  # start of the itertion loop.
  while(niter<=itermax & varmeanT<varmeanTmax & rmse>rmsemin){
    #2. -----------get the obsh......------
    varT <- apply(log(Tnew),1,var)
    meanT <- apply(log(Tnew),1,mean)
    varmeanT = var(meanT)

    # for each test and each nsim, simulate.
    obsh = samHTmcPar(grid =grid, TT=Tnew, qHT= qHT, oHT=oHT,lrw=lrw,ncore =ncore)

    #2. -----------get the obsh......------10.51  0.41 10.97

    # get the head variance for each observation.
    #3. ----------- get the covh and covhk..............
    varobsh <- apply(obsh,2,var)
    meanobsh <- apply(obsh,2,mean)
    # get the misfit.
    weigs <- 1/varobsh/sum(1/varobsh)
    rmse <- mean((trueobsh - meanobsh)^2*weigs)^0.5
    l2 <- mean((trueobsh - meanobsh)^2)^0.5
    l1 <- mean(abs(trueobsh - meanobsh))

    ## we now update the covariance calculation method.
    # obsh --- n_ensemble * n_obs.
    covh = cov(obsh) # the default is y = x
    # covh n_obs*n_obs
    tmpy = t(log(Tnew))
    covhk = cov(obsh,tmpy)
    # add stablizer term.
    #4. ----------- solve covh ..............
    covh1 <- covh
    #diag(covh1) <-  (1+mul)*diag(covh)
    diag(covh1) <-  rep((1+mul)*max(diag(covh)),nobs)
    #### now we need to invert the covariance function and get the covh-1* %*% covhf
    #a = solve(covh1,covhk[[1]])
    a = solve(covh1,covhk)
    # a in nobs*nelem

    ### now we update the k value based on the difference between obs. and sim.
    for(i in 1:nsim){
      Tnew[,i] <- Tnew[,i] *  exp( t(a) %*% (trueobsh - obsh[i,]))
    }

    msg <- paste('niter =', niter,
                 'varmeanT=', round(varmeanT,4),
                 'rmse=',round(rmse,4),
                 "l2=",round(l2,4),
                 "l1=",round(l1,4))
    msgdf <- rbind(msgdf,c(niter,varmeanT,rmse))
    #4. ----------- solve covh ..............0.42 0.07 0.49
    print(msg)
    ### we need to store the iteration data.
    iterdf[[niter]] <- list(meanT = as.vector(meanT), varT = as.vector(varT), meanobsh = meanobsh, varobsh = varobsh)
    if(niter == 1){
      et = Sys.time()
      print(" -------------------The Computational time for one iteration--------- ")
      print( difftime(et,startTime))
      print(" -------------------The Computational time for one iteration--------- ")
    }
    niter <- niter + 1
    mul <- mul/decay

    ### iteration over time.
  }
  endTime <- Sys.time()
  # get the time in seconds or mins.
  print("-------------------The Computational--------- ")
  print(difftime(endTime,startTime))
  print("-------------------The Computational--------- ")
  return(iterdf)
}


#' This function takes qHT and oHT as input and return sampled data.
#' @return Updated oHT or just one vector given the obs data.
#' @param qHT pumping test information.
#' @param oHT observation information.
#' @param TT parameter field or value.
#' @param domain a 6 * 1 vector giving (nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param TT a  n * 1 vector giving transimisivity (L2/T) at each grid point.
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @param simplify if true return vector else oHT
#' @export
#' @examples
#' domain=c(80,80,0,80,0,80)
#' grid <- GenGrid(domain=domain)
#' TT =0.1
#' data("oHT")
#' data("qHT")
#' da = samHT(grid =grid, TT=TT, qHT= qHT, oHT=oHT,lrw=320000)
samHT <- function(domain=c(40,40,0,40,0,40),
                   grid = NULL,
                   TT=0.1,
                   qHT=list(data.frame(Qp=10,x=20.5,y=20.5)),
                   oHT= list(data.frame(data=-1,x=11,y=11)),
                   lrw = 160000,
                   simplify =TRUE
 ){
  if(is.null(grid))grid = GenGrid(domain)
  nHT <- length(qHT) # number of pumping test.also list length of oHT.
  for (i in 1:nHT){
    qinf <- qHT[[i]]
    oinf <- oHT[[i]]
    trueh <- Fsteady2dsim(TT=TT,Qinf=qinf,grid=grid,lrw=lrw)$solution
    oinf = samData(grid = grid,Oinf = oinf,h=trueh)
    oHT[[i]] <- oinf[,c('data','x','y')]
  }
  if(simplify){
    oHTdf = dplyr::bind_rows(oHT,.id='id')
    return(oHTdf$data)
  }else {return(oHT)}
 }

#' This function takes qHT and oHT as input and return sampled data in monte Carlo simulation.
#' @return Updated oHT or just one vector given the obs data.
#' @param qHT pumping test information.
#' @param oHT observation information.
#' @param TT parameter field nsim * ngrid.
#' @param domain a 6 * 1 vector giving (nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param TT a  n * 1 vector giving transimisivity (L2/T) at each grid point.
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @export
#' @examples
#' domain=c(80,80,0,80,0,80)
#' grid <- GenGrid(domain=domain)
#' TT= random2d(nsim=10,grid=grid)
#' TT = TT[,-c(1,2)]
#' data("oHT")
#' data("qHT")
#' da = samHTmc(grid =grid, TT=TT, qHT= qHT, oHT=oHT,lrw=320000)
samHTmc <- function(domain=c(40,40,0,40,0,40),
                  grid = NULL,
                  TT=0.1,
                  qHT=list(data.frame(Qp=10,x=20.5,y=20.5)),
                  oHT= list(data.frame(data=-1,x=11,y=11)),
                  lrw = 160000

){
  nsim = ncol(TT)
  library('foreach')
  foreach(i =1:nsim,.combine = rbind) %do%{
    samHT(grid =grid, TT=TT[,i], qHT= qHT, oHT=oHT,lrw=lrw)
  }
}


#' This function takes qHT and oHT as input and return sampled data in monte Carlo simulation.
#' @return Updated oHT or just one vector given the obs data.
#' @param qHT pumping test information.
#' @param oHT observation information.
#' @param TT parameter field nsim * ngrid.
#' @param domain a 6 * 1 vector giving (nx,ny,x1,x2,y1,y2)
#' @param grid grid generated by GenGrid function using domain information, should give if no domain.
#' @param TT a  n * 1 vector giving transimisivity (L2/T) at each grid point.
#' @param lrw integer, the length of the real work array, default 160000 (grid size).
#' @export
#' @examples
#' domain=c(80,80,0,80,0,80)
#' grid <- GenGrid(domain=domain)
#' TT= random2d(nsim=50,grid=grid)
#' TT = TT[,-c(1,2)]
#' data("oHT")
#' data("qHT")
#' da = samHTmcPar(grid =grid, TT=TT, qHT= qHT, oHT=oHT,lrw=320000,ncore=10)
samHTmcPar <- function(domain=c(40,40,0,40,0,40),
                    grid = NULL,
                    TT=0.1,
                    qHT=list(data.frame(Qp=10,x=20.5,y=20.5)),
                    oHT= list(data.frame(data=-1,x=11,y=11)),
                    lrw = 160000,
                    ncore = 7

){
  library('foreach')
  library("doParallel")
  registerDoParallel(cores=ncore)
  nsim = ncol(TT)
  x <-foreach(i =1:nsim,.combine = rbind) %dopar%{
    HydroTomo::samHT(grid =grid, TT=TT[,i], qHT= qHT, oHT=oHT,lrw=lrw)
  }


  stopImplicitCluster()
  return(x)
}
