#' Solve 2-D steady-state groundwater flow equation
#'
#' Solves \eqn{\nabla \cdot (T \nabla h) = Q} in a 2D confined aquifer using
#' finite differences (\code{diffusion2D}) and a steady-state solver
#' (\code{rootSolve::steady.2D}).  Zero-drawdown boundary conditions are applied
#' on all four edges.  The transmissivity field \eqn{T} \code{[L\eqn{^2}/T]} may be
#' homogeneous (scalar) or heterogeneous (one value per grid cell).
#'
#' @param domain a 6-element vector \code{c(nx, ny, x1, x2, y1, y2)}.  \code{nx}
#'   and \code{ny} are the number of cells in the x and y directions;
#'   \code{x1:x2} and \code{y1:y2} are the domain extents \code{[L]}.
#' @param grid grid list generated by \code{GenGrid()}; generated from
#'   \code{domain} if \code{NULL}.
#' @param TT transmissivity \eqn{T} \code{[L\eqn{^2}/T]}.  Either a scalar (uniform
#'   field) or a length-\code{n} vector (one value per cell, ordered as
#'   \code{expand.grid(x, y)}).
#' @param Qinf a data frame with columns \code{Qp} \code{[L\eqn{^3}/T]}, \code{x} \code{[L]},
#'   \code{y} \code{[L]} giving pumping rate and location.  Positive \code{Qp} =
#'   extraction.
#' @param lrw integer, the length of the real work array passed to
#'   \code{steady.2D}.  Default 160000; increase for larger grids (rule of
#'   thumb: \eqn{\geq 100 \times n}).
#' @return A data frame with columns \code{x}, \code{y}, and \code{solution}
#'   (steady-state head/drawdown at every cell centre).
#' @export
#' @examples
#' s <- Fsteady2dsim()
#' Plotsteady2d(s,plotfile="steady2d.pdf")
#' Qinf = data.frame(Qp=c(10,10),x=c(10.5,30.5),y=c(20.5,20.5))
#' s <- Fsteady2dsim(Qinf=Qinf)
#' Plotsteady2d(s)
#' set.seed(100)
#' TT <- random2d(nsim=1)$Tp
#' s <- Fsteady2dsim(TT=TT,Qinf=Qinf)
#' Plotsteady2d(s)

Fsteady2dsim <- function(domain=c(40,40,0,40,0,40),
                         grid = NULL,
                         TT=0.1,
                         Qinf=data.frame(Qp=10,x=20.5,y=20.5),
                         lrw = 160000 )
  {

  require('rootSolve')
  # nx <- domain[1]
  # ny <- domain[2]
  # x1 <- domain[3]
  # x2 <- domain[4]
  # y1 <- domain[5]
  # y2 <- domain[6]
  # dx <- (x2-x1)/nx
  # dy <- (y2-y1)/ny
  # n <- nx * ny
  if(is.null(grid))grid = GenGrid(domain)
  n = grid$n
  nx = grid$nx
  ny = grid$ny
  dx = grid$dx
  dy = grid$dy

  Tp <- if(length(TT)==1) rep(TT,n) else TT
  Sp <- rep(1,n) # useless in steady-state solution.
  Tpm <- matrix(Tp, nx, ny)
  Spm <- matrix(Sp, nx, ny)
  h <- rep(0,n)
  h0 <- matrix(0,nx,ny)
  Qp <- Qinf$Qp
  # xmid <- seq(0.5*dx,x2-0.5*dx,by=dx)
  # ymid <- seq(0.5*dy,y2-0.5*dy,by=dy)
  # Nxp <- which.min(abs(Qinf$xp-xmid))
  # Nyp <- which.min(abs(Qinf$yp-ymid))
  Qseq <- getQseq(grid = grid,Qinf = Qinf)
  Nxp = Qseq$Nxp
  Nyp = Qseq$Nyp
  # solve the equation
  y <- rep(0,n)
  para =list(dx=dx,dy=dy,nx=nx,ny=ny,Tpm=Tpm,Spm=Spm,Qp=Qp,Nxp=Nxp,Nyp=Nyp)
  s_steady <- steady.2D(y = y, parms=para,func = diffusion2D, dimens = c(nx,ny),lrw = lrw)$y
  #xy <- expand.grid(x=xmid, y = ymid)
  xy = grid$grid
  return(data.frame(xy, solution = s_steady))
}

#' 2D groundwater diffusion residual function
#'
#' Computes the finite-difference residual of the 2D groundwater flow equation
#' \eqn{\partial h / \partial t = (1/S)\left[\nabla \cdot (T \nabla h) -
#' Q\right]}.  Called internally by \code{Fsteady2dsim()} via
#' \code{rootSolve::steady.2D()} and by \code{Ftransient2dsim()} via
#' \code{deSolve::ode.2D()}.  Transmissivity at cell interfaces is computed with
#' harmonic-mean interpolation to preserve flux continuity.  Boundary conditions
#' are zero drawdown on all four edges.
#'
#' @param t time \code{[T]} (unused in steady-state mode; required by the solver
#'   interface).
#' @param h current head vector \code{[L]}, length \code{nx * ny}.
#' @param par named list of parameters built inside \code{Fsteady2dsim()} or
#'   \code{Ftransient2dsim()}: \code{dx, dy, nx, ny, Tpm, Spm, Qp, Nxp, Nyp}.
#' @return A list containing the residual vector \eqn{\partial h / \partial t}
#'   (length \code{n}).
#' @export

diffusion2D <- function(t, h, par)   {
  with(par,{
    Dx <- (rbind(Tpm[1,],Tpm) + rbind(Tpm,Tpm[nx,])) * 0.5
    Dy <- (cbind(Tpm[,1],Tpm) + cbind(Tpm,Tpm[,ny])) * 0.5
    y    <- matrix(nr=nx,nc=ny,data=h)  # vector to 2-D matrix
    dY   <- matrix(nr=nx,nc=ny,data=0)  # initial condition
    BNDx1 <- BNDx2 <- rep(0,nx)   # boundary drawdown == 0
    BNDy1 <- BNDy2 <- rep(0,ny)   # boundary drawdown == 0
    #diffusion in X-direction; boundaries=imposed concentration: nx+1, ny
    Flux <- -Dx * rbind(y[1,]-BNDx1,(y[2:nx,]-y[1:(nx-1),]),BNDx2-y[nx,])/dx
    dY   <- dY - (Flux[2:(nx+1),]-Flux[1:nx,])/dx

    #diffusion in Y-direction
    Flux <- -Dy * cbind(y[,1]-BNDy1,(y[,2:ny]-y[,1:(ny-1)]),BNDy2-y[,ny])/dy
    dY    <- dY - (Flux[,2:(ny+1)]-Flux[,1:ny])/dy
    dY <- dY / Spm
    # add pumping rate locations.
    dY[Nxp,Nyp] <- dY[Nxp,Nyp] - Qp/dx/dy/Spm[Nxp,Nyp]

    return(list(as.vector(dY)))
  })

}
