#' Generate 2-D random field of hydraulic parameters
#'
#' Based on package gstat, it generate correlated random field using Gaussian simulation.

#' @param domain c(Nx,Ny,x1,x2,y1,y2) domain of the grid.
#' @param geo geostatistical features: list(mean,variance,covarirance_function,anisotropy,range,nugget)
#' @param nsim number of simulations.
#' @return A data frame of three elements with grid showing generated grid (in x and y) and
#'    parameter values.
#' @export
#' @examples
#' TT= random2d()
#' Plotparameter2d(TT,iflog=T)
#'  TT= random2d(geo=list(me=0,var=1,geomod="Exp",anis=c(90,0.2),range=30,nugget=0))
#' Plotparameter2d(TT,iflog=T)

random2d <- function(domain=c(40,40,0,40,0,40),
                     geo=list(me=0,var=1,geomod="Exp",anis=c(90,1),range=30,nugget=0),
                     nsim=1){

  require('gstat')
  # Nx <- domain[1]
  # Ny <- domain[2]
  # # input
  # x <- seq(domain[3],domain[4],length.out=Nx)
  # y <- seq(domain[5],domain[6],length.out=Ny)
  # xy <- expand.grid(x=x, y=y)
  grid = GenGrid(domain)
  x = grid$xmid
  y = grid$ymid
  xy = grid$grid
  me <- geo$me #mean value. lnK
  var <- geo$var # variance.
  geomod <- geo$geomod
  range <- geo$range
  nugget <- geo$nugget
  anis <- geo$anis
  m1 <- vgm(psill=var,model=geomod,range=range,anis=anis,nugget=nugget)
  g.dummy <- gstat(formula=z~1, locations=~x+y,
                   dummy=T, beta=me,
                   model=m1, nmax=20)

  # make four simulations based on the gstat object
  yy <- predict(g.dummy, newdata=xy, nsim=nsim)
  Tp <- exp(yy[,-c(1,2)])
  return(data.frame(xy,Tp))
}

#' generate forward running grid and output its grid and grid.
#'  input domain
#' @param domain c(Nx,Ny,x1,x2,y1,y2) domain of the grid.
#' @return output n, xmid, ymid, and grid
#' @export
#' @examples
#' grid <- GenGrid()
GenGrid <- function(domain=c(40,40,0,40,0,40))
{
  nx <- domain[1]
  ny <- domain[2]
  x1 <- domain[3]
  x2 <- domain[4]
  y1 <- domain[5]
  y2 <- domain[6]
  dx <- (x2-x1)/nx
  dy <- (y2-y1)/ny
  n <- nx * ny
  xmid <- seq(0.5*dx,x2-0.5*dx,by=dx)
  ymid <- seq(0.5*dy,y2-0.5*dy,by=dy)
  grid <- expand.grid(x=xmid,y=ymid)
  return(list(n=n,grid=grid,xmid = xmid, ymid = ymid,
              nx=nx,ny=ny,dx=dx,dy=dy,x1=x1,x2=x2,y1=y1,y2=y2))
}

#' Get the x- and y- directional sequence of the pumping well.
#' @param domain c(Nx,Ny,x1,x2,y1,y2) domain of the grid.
#' @param grid  grid information generated by GenGrid function.
#' @param Qinf a data.frame showing (Qp,x,y)
#' @return output x- and y- directional sequence Nxp and Nyp
#' @export
#' @examples
#' grid <- GenGrid()
#' Qseq <- getQseq(grid = grid)
#'
getQseq <- function(domain=c(40,40,0,40,0,40),
                    grid=NULL,
                    Qinf=data.frame(Qp=10,x=20.5,y=20.5)){
  Np <- length(Qinf$x)
  xmid = grid$xmid
  ymid = grid$ymid
  Nxp <- integer(length= Np)
  for(i in 1:Np){
    Nxp[i] <- which.min(abs(Qinf$x[i]-xmid))
  }
  Nyp <- integer(length= Np)
  for(i in 1:Np){
    Nyp[i] <- which.min(abs(Qinf$y[i]-ymid))
  }
  Qinf$Nxp = Nxp
  Qinf$Nyp = Nyp
  return(Qinf)
}

#' Get the elemental number of the observation well.
#' @param domain c(Nx,Ny,x1,x2,y1,y2) domain of the grid.
#' @param grid  grid information generated by GenGrid function.
#' @param Oinf a data.frame showing (data = null, x,y)
#' @return output elemental number of the observation wells.
#' @export
#' @examples
#' grid <- GenGrid()
#' Oinf <- getOelem(grid = grid)
#'
getOelem <- function(domain=c(40,40,0,40,0,40),
                    grid =NULL,
                    Oinf=data.frame(data=NA,x=30.5,y=30.5)){
  No <- length(Oinf$x)
  xmid = grid$xmid
  ymid = grid$ymid
  Nxo <- integer(length= No)
  for(i in 1:No){
    Nxo[i] <- which.min(abs(Oinf$x[i]-xmid))
  }
  Nyo <- integer(length= No)
  for(i in 1:No){
    Nyo[i] <- which.min(abs(Oinf$y[i]-ymid))
  }
 ### return the actual element number... numbering from lowerleft to upperright.
  nelem = (Nyo - 1) * grid$nx +Nxo
  Oinf$nelem = nelem
  return(Oinf)
}

#' generate forward running grid and output its grid and observation/source grid.
#'  input domain, pump and obs location
#' @param domain c(Nx,Ny,x1,x2,y1,y2) domain of the grid.
#' @param pump c(xp,yp) pump location.
#' @param obs c(xo,yo) observation location.
#' @return output grid, pump and obs element number
#' @export
#' @examples
#' grid <- GenGrid()
GenGrid2 <- function(domain=c(40,40,0,40,0,40),
                    pump=list(xp=20.5,yp=20.5),
                    obs=list(xo=30,yo=30))
{
  nx <- domain[1]
  ny <- domain[2]
  x1 <- domain[3]
  x2 <- domain[4]
  y1 <- domain[5]
  y2 <- domain[6]
  dx <- (x2-x1)/nx
  dy <- (y2-y1)/ny
  n <- nx * ny
  xmid <- seq(0.5*dx,x2-0.5*dx,by=dx)
  ymid <- seq(0.5*dy,y2-0.5*dy,by=dy)
  grid <- expand.grid(x=xmid,y=ymid)
  Nxp <- which.min(abs(pump$xp-xmid))
  Nyp <- which.min(abs(pump$yp-ymid))
  Nxo <- which.min(abs(obs$xo-xmid))
  Nyo <- which.min(abs(obs$yo-ymid))
  return(list(n=n,grid=grid,pump=c(Nxp,Nyp),obs=c(Nxo,Nyo)))
}




#' sample obs for synthetic data.
#' @export
#' @param loc_obs c(elem1,elem2) elem number of the observation
samData <- function(loc_obs=c(1,2),h=rnorm(10)){
  obs <- h[loc_obs]
  return(obs)
}
